### ISSUE TITLE
tab is empty and all other values empty in appdaemon dash

### ISSUE THREAD

**Issue by bacarrdy** [ciotlosm/lovelace-thermostat-dark-card#266]
My config looks very simple now while testing. After restarting appdaemon i can see only clock (i have bolded in layout that at end i`m loading climatecontrol_test)

title: TEST TITLE
widget_dimensions: [120, 120]
widget_size: [1, 1]
widget_margins: [5, 5]
columns: 8

resources:
  - url: /local/community/lovelace-thermostat-dark-card/thermostat-dark-card.js
    type: module

climatecontrol_test:
  - type: custom:thermostat-card
    entity: climate.2au_hvac_test_mode
    chevron_size: 100
    step: 1
    highlight_tap: true
    no_card: true

global_parameters:
    use_comma: 0
    precision: 1
    use_hass_icon: 1
    namespace: default
    devices:
      media_player:
        step: 5

layout:
  - clock.clock (2x2),sensor.2au_hvac_test_air_temperature,sensor.2au_hvac_test1_air_temperature,sensor.2au_hvactest2_air_temperature,sensor.2au_hvac_test3_air_temperature
  - sensor.2a_trisens_test_k_air_temperature,sensor.2au_multisens_test1_air_temperature,sensor.2au_trisens_test2_air_temperature,**climatecontrol_test (2x2)**

**Comment by ciotlosm** [comment]
@bacarrdy if you are using the new version (compiled version in releases), you should switch to using: `custom:thermostat-dark-card`

**Comment by bacarrdy** [comment]
i have tryed that before reporting bug:

  - type: custom:thermostat-dark-card

i`m using docker and installed from HACS
I`m quite new with hassio, but seems i checked everything many times and should work

**Comment by ciotlosm** [comment]
This URL might be wrong: `/local/community/lovelace-thermostat-dark-card/thermostat-dark-card.js`
Try using the one HACS recommends you on install

**Comment by bacarrdy** [comment]
resources:
  - url: /hacsfiles/lovelace-thermostat-dark-card/thermostat-dark-card.js
    type: module

climatecontrol_test:
  - type: custom:thermostat-dark-card
    entity: climate.2au_hvac_darbo_k_mode
    title: test
    step: 1

Tryed minimal version and followed your instruction to find out correct directory, but i still have same issue an notihing in logs

**Comment by ciotlosm** [comment]
@bacarrdy can you check javascript console on the browser? If nothing works, I'm happy to try a debugging session on discord (hacs discord).

**Comment by bacarrdy** [comment]
`jquery-3.1.1.min.js:2 jQuery.Deferred exception: Unable to process binding "text: function(){return error }"
Message: error is not defined ReferenceError: Unable to process binding "text: function(){return error }"
Message: error is not defined
    at text (eval at parseBindingsString (http://192.168.1.201:5050/javascript/knockout-3.4.1.js:68:172), <anonymous>:3:57)
    at update (http://192.168.1.201:5050/javascript/knockout-3.4.1.js:98:202)
    at a.B.i (http://192.168.1.201:5050/javascript/knockout-3.4.1.js:72:379)
    at Function.Qc (http://192.168.1.201:5050/javascript/knockout-3.4.1.js:51:391)
    at Function.Rc (http://192.168.1.201:5050/javascript/knockout-3.4.1.js:51:155)
    at Function.aa (http://192.168.1.201:5050/javascript/knockout-3.4.1.js:50:502)
    at Object.a.m.a.B (http://192.168.1.201:5050/javascript/knockout-3.4.1.js:49:67)
    at http://192.168.1.201:5050/javascript/knockout-3.4.1.js:72:366
    at Object.q (http://192.168.1.201:5050/javascript/knockout-3.4.1.js:11:244)
    at m (http://192.168.1.201:5050/javascript/knockout-3.4.1.js:71:428) undefined
r.Deferred.exceptionHook @ jquery-3.1.1.min.js:2
k @ jquery-3.1.1.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.1.1.min.js:2
i @ jquery-3.1.1.min.js:2
fireWith @ jquery-3.1.1.min.js:2
fire @ jquery-3.1.1.min.js:2
i @ jquery-3.1.1.min.js:2
fireWith @ jquery-3.1.1.min.js:2
ready @ jquery-3.1.1.min.js:2
R @ jquery-3.1.1.min.js:3
jquery-3.1.1.min.js:2 Uncaught ReferenceError: Unable to process binding "text: function(){return error }"
Message: error is not defined
    at text (eval at parseBindingsString (knockout-3.4.1.js:68), <anonymous>:3:57)
    at update (knockout-3.4.1.js:98)
    at a.B.i (knockout-3.4.1.js:72)
    at Function.Qc (knockout-3.4.1.js:51)
    at Function.Rc (knockout-3.4.1.js:51)
    at Function.aa (knockout-3.4.1.js:50)
    at Object.a.m.a.B (knockout-3.4.1.js:49)
    at knockout-3.4.1.js:72
    at Object.q (knockout-3.4.1.js:11)
    at m (knockout-3.4.1.js:71)
text @ VM883:3
update @ knockout-3.4.1.js:98
a.B.i @ knockout-3.4.1.js:72
Qc @ knockout-3.4.1.js:51
Rc @ knockout-3.4.1.js:51
aa @ knockout-3.4.1.js:50
a.m.a.B @ knockout-3.4.1.js:49
(anonymous) @ knockout-3.4.1.js:72
q @ knockout-3.4.1.js:11
m @ knockout-3.4.1.js:71
h @ knockout-3.4.1.js:69
g @ knockout-3.4.1.js:69
h @ knockout-3.4.1.js:70
a.Sb @ knockout-3.4.1.js:76
WidgetBase @ dashboard.js:370
baseerror @ application.js:1534
(anonymous) @ heat_init.js:79
j @ jquery-3.1.1.min.js:2
k @ jquery-3.1.1.min.js:2
setTimeout (async)
r.readyException @ jquery-3.1.1.min.js:2
(anonymous) @ jquery-3.1.1.min.js:2
j @ jquery-3.1.1.min.js:2
k @ jquery-3.1.1.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.1.1.min.js:2
i @ jquery-3.1.1.min.js:2
fireWith @ jquery-3.1.1.min.js:2
fire @ jquery-3.1.1.min.js:2
i @ jquery-3.1.1.min.js:2
fireWith @ jquery-3.1.1.min.js:2
k @ jquery-3.1.1.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.1.1.min.js:2
i @ jquery-3.1.1.min.js:2
fireWith @ jquery-3.1.1.min.js:2
fire @ jquery-3.1.1.min.js:2
i @ jquery-3.1.1.min.js:2
fireWith @ jquery-3.1.1.min.js:2
ready @ jquery-3.1.1.min.js:2
R @ jquery-3.1.1.min.js:3
`

![Capture](https://user-images.githubusercontent.com/8859510/100071331-973d5e00-2e43-11eb-895c-b03655b15a6c.PNG)

**Comment by ciotlosm** [comment]
The error there seems to be related to some other system on your setup. The card is not displaying probably because Javascript errors out before it gets to processing the card. Could you check whatever is using that Knockout and remove it temporary to see if the card works?
